tailscale_auth_key: ENC[AES256_GCM,data:K6QOE3GiRswVf3+7eTbQgpEUkHW6Y7Ha6ZOQaAUeTis6bNTfPjv/NjL0Y02DDgpiOnANZGSC4TKSSSaEPA==,iv:ZVIJcU39kXCn8UmzA+tk9cDfC0cK//eM9hdRNstz3O0=,tag:Wi9JLWjkQYdhAUTidMYXag==,type:str]
#ENC[AES256_GCM,data:K1Y+3B9lQhVU7JvFJUnKGO0kEWuBFYpkj9VU5t05V/S5iobc21O/CRT0oSxqFCUhLTPLEi4BdyhhNYIIxEmPU3GPS6qYDpAoCtI=,iv:ZUi+HfVHU//wMa4ESXdAqL4nxn+e5RkD+UoC8LFAoHk=,tag:AO0wFQQY4cUtdGUVeQQz9w==,type:comment]
#ENC[AES256_GCM,data:1QWk79ECJP9vhjQN2JWq8PRawy/94Ujtt1FFam9KTnQr4GvJ+478X5sL7kM+UOpO8tidj89RvbstNxP52VnjOo/OlXZnMCAWxVA=,iv:/NyZEVzPl78rzJHfCkywGZRDI7lnHdQigFi2iTNgLXw=,tag:9L7DcyEQeUrHYvPABFB/6Q==,type:comment]
#ENC[AES256_GCM,data:IJWizQ8gRiAlsqE0yxdyfW3P8mvFTMbuO1PDneV6NxDbY3sn+lm8dI4AxfI5rkECRK/kNw1YQgqmpUXBwUF+63CPYisszw5BvKNAw6bGxA==,iv:edC5dPYBS7N1XNVtqLRDwucuPnu7zMSPSeW2rQTVpNs=,tag:+v23JiHed0fopPIDIYyYww==,type:comment]
komodo_onboarding_key: ENC[AES256_GCM,data:JkLcj2RR4zaHACs9AV0wPd7v3nH42bYyrCpVEOrfOEs=,iv:M6f1VQCdTd6x+1ToQty0kLcrEnozrHhde7z9HWu+ZgM=,tag:5yGIBG1X88PVkSRGD88+ZQ==,type:str]
searxng_secret: ENC[AES256_GCM,data:U+CDawl5u67PW1RFwbNF/YrDziVOIsGmVfdDFm0kPkyUH7xrnil0Srb3zkpqMUk4YzZmYrwiBIR9nhA6pcu7EQ==,iv:S28VMWpzD7HNm1A4DoJP5p4d3q+UfnD/XzUe6z0VNOY=,tag:LIt5vbcb5H7I0sGxDtTygQ==,type:str]
flame_password: ENC[AES256_GCM,data:/XwufnJBsvPkozkr41BLnq6MdqOwLud1md3Uq8wCEzc=,iv:TqQJ1DShAyLTDUG5R16DLJizOVIuJZQ5eNbTiefimaE=,tag:osDJximKoPvasGeQWQSqeQ==,type:str]
vaultwarden_admin_token: ENC[AES256_GCM,data:r4yCaIHGqsKJOiMHU5MxzQOBunEcThby5EMt/2Ymas9REVIbQSKvOGS068SyxpS8,iv:Eu8p2ARvY8J5iKBJUEKy6e3QpARqxRPtpS5+nZm0XdA=,tag:2RGC3jBz4HdERm8y2c6yIw==,type:str]
dawarich_secret_key_base: ENC[AES256_GCM,data:ZKnev0OdHIHj/uQ0tPxlw9yhvPRkk6Pt0oARl8TvkKFi5aoBouYultxL9eLkuxd8XG78809vwyHHc8YVOUhASwaTjl4VZjRQFdOJk/KrslqjjU962UJNVmMYd33GlRDliSWlUz9IBxDJHU9RY3c5Mygio8HwS1DgGqmeDLCy5eY=,iv:pFGgAsIj2Fopl8JmA3UOzBxCLM59tfkfl4vNXjgsRlM=,tag:YvAoRY5tC4nBwDeQt0eTkw==,type:str]
dawarich_db_password: ENC[AES256_GCM,data:7JD42ZURSVXCYQCALrlAdOa9Pr98altOv/xOlteRBh3PMyrT1sB2bdbRsn/NDQWo,iv:srLBTfPE5YeheY7sn1n4CDwQ9Yt3RTCkGuqz0RwalCc=,tag:BwpTdPIK0wtEiTjPaIlsxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWWcvNE83aXJNd1hteWVT
            UW9GNWYyVy90M3RmWmpqWmhHTkNad3hPOHk4CkRhY3NLeklsZWtZNElSU0g2S0gz
            ZFd4SE55K2xIMWxzWm5aVlZSMG5PdUUKLS0tIG8zOGcvVlRpc1R2NkFkRk9QYTJ4
            NDBNSEVRbFNzODFTbEpIT0VhaTRDV0EKEKTtD6SNlJHJMN8IUhX15y0AD9r1gbGI
            knDQbLJyQHbApOTBvTF8c9mWl9CtTB8Z+74XXIjPLvchuEXqfnq1xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12f27dnat4w09xcad3wrwxj0e84zgd5vupwc996gw4u42tdjaas6qj5yu7m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbHBPKzMvaDRzMkhST1Vk
            QzdhRlhiWDFIY1pHcWxMQ3Z0dVN4Wlk1Q0NnClp0Rmo4a3lFU1BFaXZYOHA1S1E0
            YXF1TGk0WGlDbTcwcXdTQWVuamxQSVUKLS0tIHNieHBnNkFzM1JHN1pnZS9xZUJG
            NllHNE1ESERBdmFlbjNVUUFJUHhCYnMKk/54VaqPjuABgc7cYyEGTGuJGnoFGQ9H
            jnHkzmW8ZM+aQzTXVOULLbxUoEZf1KVrKCWCW5zDBHRSyVv4son0LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pfdamnetdjntyxdcrmlmlg4xealmf7urhuxdt7g3mvrpxjy6kfpqumf6na
    lastmodified: "2026-09-17T14:18:14Z"
    mac: ENC[AES256_GCM,data:o1oRD8W8vKcuPlthXwA3BwMstbIdp1s0Sj12QnuyOnMvUmjfGbUFBqIwt56b205lxC1nJbtY/guonsybsSF6H+toK6R6REfa0bPT5MlYf0+Pgu7M9psJL8PDqT68qPFsQmfnEzgNGN1Uln2CNj2tY87rPw0eyvnaJ9BNZSE8llE=,iv:bFcTOmfZziPJyj+vtA8fDXkm02MNJOofbXqmsRuDJVM=,tag:IL642lC8P+4arRsMimhY3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
