tailscale_auth_key: ENC[AES256_GCM,data:Fl/2c/VWDSA3IasBoAGwLCXBmORAQ/nH3WmQX+RgZFKXBJFCkW1aKszX5u2BKKOk5PVbjFunWEXkB7LldA==,iv:1J7XoklxYoas6ZOJEpQlwVp0u7MUy+cNjdpeNejhR6I=,tag:mv6OOxds1jwQMcDOB8VyJg==,type:str]
#ENC[AES256_GCM,data:K1Y+3B9lQhVU7JvFJUnKGO0kEWuBFYpkj9VU5t05V/S5iobc21O/CRT0oSxqFCUhLTPLEi4BdyhhNYIIxEmPU3GPS6qYDpAoCtI=,iv:ZUi+HfVHU//wMa4ESXdAqL4nxn+e5RkD+UoC8LFAoHk=,tag:AO0wFQQY4cUtdGUVeQQz9w==,type:comment]
#ENC[AES256_GCM,data:1QWk79ECJP9vhjQN2JWq8PRawy/94Ujtt1FFam9KTnQr4GvJ+478X5sL7kM+UOpO8tidj89RvbstNxP52VnjOo/OlXZnMCAWxVA=,iv:/NyZEVzPl78rzJHfCkywGZRDI7lnHdQigFi2iTNgLXw=,tag:9L7DcyEQeUrHYvPABFB/6Q==,type:comment]
#ENC[AES256_GCM,data:IJWizQ8gRiAlsqE0yxdyfW3P8mvFTMbuO1PDneV6NxDbY3sn+lm8dI4AxfI5rkECRK/kNw1YQgqmpUXBwUF+63CPYisszw5BvKNAw6bGxA==,iv:edC5dPYBS7N1XNVtqLRDwucuPnu7zMSPSeW2rQTVpNs=,tag:+v23JiHed0fopPIDIYyYww==,type:comment]
komodo_onboarding_key: ENC[AES256_GCM,data:JkLcj2RR4zaHACs9AV0wPd7v3nH42bYyrCpVEOrfOEs=,iv:M6f1VQCdTd6x+1ToQty0kLcrEnozrHhde7z9HWu+ZgM=,tag:5yGIBG1X88PVkSRGD88+ZQ==,type:str]
searxng_secret: ENC[AES256_GCM,data:U+CDawl5u67PW1RFwbNF/YrDziVOIsGmVfdDFm0kPkyUH7xrnil0Srb3zkpqMUk4YzZmYrwiBIR9nhA6pcu7EQ==,iv:S28VMWpzD7HNm1A4DoJP5p4d3q+UfnD/XzUe6z0VNOY=,tag:LIt5vbcb5H7I0sGxDtTygQ==,type:str]
flame_password: ENC[AES256_GCM,data:/XwufnJBsvPkozkr41BLnq6MdqOwLud1md3Uq8wCEzc=,iv:TqQJ1DShAyLTDUG5R16DLJizOVIuJZQ5eNbTiefimaE=,tag:osDJximKoPvasGeQWQSqeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLakFlK3VMZitzdTRTWlAz
            WjgrTEtybUNldlFuTWh1RzNXRTVxaVg0eURnCksvTlZ4V2I0cjcyV2NERXo1Wkx0
            aTlpRDU1ZzlmTkE0dlBrRkNZWklPak0KLS0tIDNSaS9wRU8rQm1sUWtFMlphejNr
            ZkdVWnY1d2c0YjRFTnhIWGZxQmVSTWcKTzTpE2Tvm9mRGmdrwHV9E5sxdN0zdZzl
            cn9cZWdP7CtzZWioiguSuhBJ0XbflDmmxKhs9DH90ckfkToeMgEaZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12f27dnat4w09xcad3wrwxj0e84zgd5vupwc996gw4u42tdjaas6qj5yu7m
    lastmodified: "2026-09-17T12:26:05Z"
    mac: ENC[AES256_GCM,data:8LABAVB/fJGDh4e9m3cTzc/c5ijm9d4DfN4kbtswEiUI7LUDvWTyWd2FX15vHVg8wKdBzEhO02qVEJDZd/daOQywzaCzpKylchDLZF0tNZN9s9IWRBHTXbZr2I6haquhkcfW7wvZ9EC0XFOXAz9q3VT3kaTJRlTg5cK3eNEtC5Y=,iv:ekJD6iacI93FOSXLZIb7XXhYbj3Al4+KGD5+G/zsSq4=,tag:EPehebQJbLfSu4No9y3tjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
